1. Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 

In [16]:
num_seq=input("Enter sequence of comma separated numbers: ")
print("Input Sequence: ", num_seq)
list1=num_seq.split(',')
print("List1: ",list1)
ipvec=[]
for i in list1:
    ipvec.append(int(i))
print("Output: ", ipvec)

print(len(ipvec))
colno=int(input("Enter the number of columns: "))
   
def matrix(ipvec, n, increasing=True):
    if increasing:
        op_matx=[i**(n-1-j) for i in ipvec for j in range(n)]
    elif not increasing:
        op_matx=[i**j for i in ipvec for j in range(n)]
    return op_matx

matx1=matrix(ipvec,colno,False)
matx3=np.reshape(matx1,(len(ipvec),colno))
matx2=matrix(ipvec,colno,True)
matx4=np.reshape(matx2,(len(ipvec),colno))

print("The input array i s:",ipvec)
print("Column numbers :",colno)
print("Matrix : \n",matx3)
print("Reverse matrix :\n",matx4)


Enter sequence of comma separated numbers: 1,3,5,7,9
Input Sequence:  1,3,5,7,9
List1:  ['1', '3', '5', '7', '9']
Output:  [1, 3, 5, 7, 9]
5
Enter the number of columns: 4
The input array i s: [1, 3, 5, 7, 9]
Column numbers : 4
Matrix : 
 [[  1   1   1   1]
 [  1   3   9  27]
 [  1   5  25 125]
 [  1   7  49 343]
 [  1   9  81 729]]
Reverse matrix :
 [[  1   1   1   1]
 [ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]
 [729  81   9   1]]
